language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - npm install

script:
  - cat .pwd | base64 --decode | docker login -u yechenglin --password-stdin
  - docker build -t yechenglin/mydev.latest .
  - docker push yechenglin/mydev.latest
